### ISSUE TITLE
proxy error

### ISSUE THREAD

**Issue by stuPETER12138** [Nexseer/zed-config#1]
After I added "proxy": "http://127.0.0.1:7890", 'to the settings.json file and restarted Zed Editor, I can`t connect the server and sign in with my github account. How can I make it work?

![Screenshot from 2024-10-17 11-23-12](https://github.com/user-attachments/assets/9d487e54-3402-4181-9f9b-1692083a4d97)

**Comment by Nexseer** [comment]
If you need to use a proxy, then different proxy tools have different proxy ports, the clash series has port 7890, modify it to suit your specific situation.
There is nothing wrong with this syntax, see if your proxy tool is working!

**Comment by stuPETER12138** [comment]
OK, I understand, thank you!🫡
